student/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from student.views import base,signin, signout, signup, create_assignment, assignment_submission,submitted,\
    delete_assignment, edit_assignment,Assignmentsubmit, student_submitted,submit_button

app_name = "student"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', base, name="base"),
    path('', signin, name="signin"),
    path('signout/', signout, name="signout"),
    path('signup/', signup, name="signup"),
    path('teachers/', create_assignment, name="teachers"),
    path('students/', assignment_submission, name="students"),
    path('submitted/(?P<id>[0-9]+)/$', submitted, name="submitted"),
    path('submitted/', student_submitted, name="student_submitted"),
    path('detail/<pk>/', Assignmentsubmit.as_view(),name="assignment-detail"),
    path('delete/(?P<id>\d+)/$', delete_assignment, name='delete_assignment'),
    path('edit/(?P<id>[0-9]+)/$', edit_assignment, name='edit_assignment'),
    path('submit/(?P<id>[0-9]+)/$', submit_button, name='submit_button'),

]

task2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from builtins import property

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
from django.db import models
from django.contrib.auth.models import PermissionsMixin


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email)
        user.is_admin = True
        user.set_password(password)
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    full_name = models.CharField(max_length=250, blank=True, null=True)
    teacher = models.BooleanField(default=True)
    student = models.BooleanField(default=False)
    college_name = models.CharField(max_length=225, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    objects = MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.full_name

    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return self.is_admin

    @property
    def is_teacher(self):
        return self.teacher

    @property
    def is_student(self):
        return self.student


class Assignment(models.Model):
    title = models.CharField(max_length=255)
    upload = models.FileField(upload_to='assignments/', null=True, default="No file uploaded", blank=True)
    due_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)
    course_code = models.CharField(max_length=8)
    course_title = models.CharField(max_length=255)
    user = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name='assignments'
    )

    def __str__(self):
        return self.title


class Submission(models.Model):
    description = models.CharField(max_length=100, null=True, blank=True, default="No description")
    upload = models.FileField(upload_to='submissions/', blank=True)
    submitted_at = models.DateField(default=None)
    last_updated = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.CASCADE,
        related_name='submissions'
    )
    user = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name='submissions'
    )

    def __str__(self):
        return str(self.assignment_id)

student/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from student.models import MyUser, Assignment, Submission


class SignupForm(UserCreationForm):
    choice = forms.ChoiceField(choices=[('student', 'Student'), ('teacher', 'Teacher')])

    class Meta:
        model = MyUser
        fields = ["full_name", "email", "college_name", "choice"]


class SigninForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        fields = ['username', 'password']


class AssignmentForm(ModelForm):
    upload = forms.FileField(
        required=False,
        label='Select a file',
        help_text='max.200 megabytes'
    )
    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = Assignment
        fields = ["title", "course_code", "course_title", "upload", "due_date"]


class SubmissionForm(ModelForm):
    upload = forms.FileField(required=True)

    class Meta:
        model = Submission
        fields = ["assignment", "upload", "description", "submitted_at"]

student/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from student.models import Assignment, Submission, MyUser
from student.forms import SignupForm, SigninForm, AssignmentForm, SubmissionForm

def signup(request):
    if request.user.is_authenticated:
         messages.info(request, "User already logged in")
         return redirect("student:base")
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            value = form.save(commit=False)
            if request.POST.get('choice')=='student':
                value.student=True
                value.teacher=False
            else:
                value.student = False
                value.teacher = True
            value.save()
            messages.success(request, "User created successfully")
            return redirect("student:signin")
        else:
            messages.info(request, "Invalid form")
    else:
        form = SignupForm()
    return render(request, "student/signup.html", {"form": form})

def signin(request):
    if request.user.is_authenticated:
        messages.info(request, "User already logged in")
        return redirect("student:base")
    if request.method == "POST":
        form = SigninForm(request.POST)
        username = form["username"].value() # req.POST.get('username')
        password = form["password"].value()
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully logged in")
        else:
            messages.error(request, "Invalid Username or Password")

        if user.student == True:
            return redirect('student:base')
        else:
            creation = AssignmentForm()
            return redirect('student:base')
    else:
        form = SigninForm()
    return render(request, "student/signin.html", {"form":form})


@login_required(login_url='/signin')
def create_assignment(request):
    if request.user.teacher == True:
     if request.method == "POST":
            form = AssignmentForm(request.POST ,request.FILES or None)
            if form.is_valid():
                value = form.save(commit=False)
                value.user_id = request.user.id
                value.save()
                messages.success(request, "Assignment uploaded successfully")
                return redirect("student:base")
     else:
            form = AssignmentForm()
            profile = MyUser.objects.get(id=request.user.id)

            return render(request, "student/teacher.html", {"form": form,'profile':profile})
    else:
        raise Http404

@login_required(login_url='/signin')
def assignment_submission(request):
    if request.user.student == True:
        if request.method == "POST":
            form = SubmissionForm(request.POST or None,request.FILES)
            if form.is_valid():
                value = form.save(commit=False)
                value.user_id = request.user.id
                value.save()
                messages.success(request,"Assignment submitted successfully")
                return redirect("student:student_submitted",)

            else:
                messages.info(request, "form is invalid")
                form = SubmissionForm()
                return render(request, "student/students.html", {"form": form})
        else:
            form = SubmissionForm()
            profile = MyUser.objects.get(id=request.user.id)
            return render(request, "student/students.html", {"form": form,'profile':profile})
    else:
        raise Http404
def submit_button(request,id):
    if request.user.student == True:
        if request.method == "POST":
            form = SubmissionForm(request.POST or None,request.FILES)
            if form.is_valid():
                value = form.save(commit=False)
                value.user_id = request.user.id
                value.save()
                messages.success(request,"Assignment submitted successfully")
                return redirect("student:student_submitted",)

            else:
                messages.info(request, "form is invalid")
                form = SubmissionForm()
                return render(request, "student/students.html", {"form": form})
        else:
            form = SubmissionForm()
            profile = MyUser.objects.get(id=request.user.id)
            return render(request, "student/students.html", {"form": form,'profile':profile})
    else:
        raise Http404
@login_required(login_url='/signin')
def signout(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect("student:signin")

def delete_assignment(request, id=None):
    if request.user.is_authenticated:
        instance = get_object_or_404(Assignment,id=id)
        instance.delete()
        messages.success(request,'post deleted')
        return redirect("student:base")
    else:
        messages.info(request, "You need to be authenticated to perform this operation.")
        return redirect("student:signin")

def edit_assignment(request,id=None):
    if request.user.is_authenticated:
        instance = Assignment.objects.get(id=id)
        aform = AssignmentForm(request.POST or None, request.FILES or None,instance=instance)
        context = {
            'form': aform,
        }
        if aform.is_valid():
            instance = aform.save(commit=False)
            instance.save()
            messages.success(request, 'Assignment was successfully edited.')
            return redirect('student:base')

    else:
        messages.info(request, "You need to be authenticated to perform this operation.")
    return render(request, "student/teacher.html", context)

def submitted(request,id):
        if request.user.is_authenticated:
            submissions = Submission.objects.filter(assignment_id=id)
            data = {"submit": submissions, }
            return render(request, "student/submission.html", data)
        else:
            messages.info(request, "You need to login to view the submitted page.")
            return redirect("student:signin")

def student_submitted(request):
    if request.user.is_authenticated:
        submissions = Submission.objects.filter(active=True)
        data = {"submit": submissions, }
        return render(request, "student/submission.html", data)
    else:
        messages.info(request, "You need to login to view the submitted page.")
        return redirect("student:signin")

def base(request):
        assignments = Assignment.objects.filter(active=True)
        submissions = Submission.objects.filter(active=True)
        profile = MyUser.objects.get(id=request.user.id)
        context = {"context": assignments,"submit": submissions, "profile": profile}
        return render(request, 'student/base.html', context)

class Assignmentsubmit(DetailView):
    model = Submission
    template_name = 'student/detail.html'

student/templates/student/base.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    {% load bootstrap4 %}
  {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
      <title>{% block title %}Assignment Management System{% endblock %}</title>
  </head>

<nav class="navbar-expand-sm bg-dark navbar-dark sticky-top" style="background-color:  #87ceeb;">
<a class="navbar-brand" href="/">Assignment System</a>
    <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'student:base'  %}">Home</a>
                {% else %}
              <a class="nav-link" href="/"></a>
                {% endif %}
            </li>
          <li class="nav-item">
                {% if profile.student %}
              <a class="nav-link" href="{% url 'student:students' %}">Submit</a>
                {% elif profile.teacher %}
              <a class="nav-link" href="{% url 'student:teachers' %}">Create</a>
                    {% else %}
                    <a class="nav-link" href="/">
                    </a>
                {% endif %}
          </li>
              <li class="nav-item" >
                {% if request.user.is_authenticated %}
              <a class="nav-link"  href="{% url 'student:signout' %}">LogOut</a>
                {% else %}
              <a class="nav-link" href="/"></a>
                {% endif %}
              </li>
          </ul>
        </div>
    </nav>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    </div>
</div>
{% block content %}
    {% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
    <div class="container">
      <div class="row" style="margin-top: 60px">
        <div class="col-lg-12 col-md-12 col-sm-12">
          {% bootstrap_messages %}
          <div class="row">
              {% for item in context %}
                  <div class="col-md-4" style="margin-left:0px">
                  <div class="card" style="margin-bottom: 10px;width: 300px">
                      <div class ="card-header"><b>Assignment Title:</b><br>
                          {% if profile.teacher %}
              <a href="{% url 'student:submitted' id=item.id %}">{{ item.title }}</a>
                {% else %}
             <p>{{ item.title}}</p>
                {% endif %}
                      </div>
              <div class="card-body">
                  <p class="card-title"><b>Course Title:</b>{{ item.course_title }}</p>
                                <p class="card-title"><b>Assigned by:</b>{{ item.user.full_name }}</p>
                  <a href="{{ MEDIA_URL }}{{ item.upload.url }}">Download assignment</a>
                  <p class="card-text"><b>Due-Date:</b>{{ item.due_date }}</p>
                  <p class="card-text"><b>Created_at:</b>{{ item.created_at}}</p>
              {% if profile.student %}
                  <a class="btn  btn-outline-info btn-edit"
                href="{% url 'student:submit_button' item.pk %}"
           name="submit_button">submit</a>
              {% elif profile.teacher %}
                  <div class = "row">
                  <div style="display:flex;flex-direction: row;width:100%">
                  <div style="width:50vw;text-align: center">
<a class="btn  btn-outline-info btn-edit" style="width: 80px"
                href="{% url 'student:edit_assignment' item.pk %}"
           name="edit-assignment">Edit</a>
                  </div>
                  <div style="width:50vw;text-align: center">
                  <form method="POST" action={% url 'student:delete_assignment' id=item.id %}>
                      {% csrf_token %}
      <button class="btn btn-outline-danger btn-delete"  style="width: 80px" type="submit" name="delete-assignment">Delete</button>
                  </form></div>
                  </div>
                </div>
                                  {% else %}
<a href="#"></a>
                {% endif %}
              </div>
            </div>
                  </div>
              {% endfor %}
          </div>
          </div>
        </div>
    </div>
{% endblock%}
</body>
</html>

student/templates/student/detail.html
{% extends "student/base.html" %}
{% block content %}
    {% load bootstrap4 %}

    <div class="container">
      <div class="row" style="margin-top: 60px">
        </div>
        <div class="col-lg-9 col-md-8 col-sm-12">
          {% bootstrap_messages %}
          <div class="row">
                              <div class="card col-lg-4 col-md-6 col-sm-12" style="margin-right: 20px" >
              <div class="card-body">
                <h6 class="card-title"><b>Assignment:</b>{{ object.assignment}}</h6>
                  <a href="{{ MEDIA_URL }}{{ object.upload.url }}">Uploaded assignment</a>
                  <p class="card-text"><b>Description:</b>{{ object.description }}</p>
                                  <p class="card-text"><b> Assigned by:</b>{{ object.assignment.user.full_name }}</p>
                                   <p class="card-text"><b>Submitted by:</b>{{ object.user.full_name }}</p>
                                    <p class="card-text"><b>Submitted at:</b>{{ object.submitted_at }}</p>
              </div>
            </div>
          </div>
        </div>
    </div>

{% endblock%}

student/templates/student/signin.html
{% extends "student/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% block content %}
<title>
{% block title %}Login To system{% endblock %}
</title>

    <div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5" style="background-color: rgba(0,0,0,0.1);color: black;">
                <div class="card-header text-center">
                    Login to your account
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}

                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Sign In">

                        <div style="text-align: center;">
                        <a class = "btn btn-info " href="{% url "student:signup" %}"
                           class="float-right small">Sign Up</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>

student/templates/student/signup.html
{#{% extends "student/base.html" %}#}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<title>
    {% block title %}SignUp to system{% endblock %}
</title>
{% block content %}
<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Sign Up to system
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <input type="submit"
                               class="btn btn-success text-center w-100 mb-3"
                               value="Sign Up">
                         <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
                        <a href="{% url "student:signin" %}"
                           class="small">Sign In</a>
                        <a href="/" class="float-right small">Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/students.html
{% extends "student/base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
<h1>Assignment submission</h1>
                    <p>Please Submit your assignment here.</p></div>
                    <div class="card-body">
<form action="#" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success text-center w-100 mb-3"
             value="submit">
</form>
  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/submission.html
{% extends "student/base.html" %}
{% block content %}
    {% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
          {% bootstrap_messages %}
    <div class="container">
         <h2>Assignment List</h2>
        <table class="table">
    <thead>
      <tr>

        <th> Assignment</th>

        <th> Submited by</th>


      </tr>
    </thead>
    <tbody>

    {% for item in submit %}
    <td>
        <a href="{% url 'student:assignment-detail' item.pk%}">{{item.assignment}}</a></td>
    <td>{{item.user.full_name }}</td>


    </tbody>


    </div>

{% endfor %}
{% endblock%}

student/templates/student/teacher.html
{% extends "student/base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
<h1>Assignment Creation</h1>
                    <p>Add assignment here.</p></div>
                    <div class="card-body">
<form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success text-center w-100 mb-3"
             value="submit">
</form>
  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}